// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/09       [394761]
Creator        : tt8888tt
Date           : Fri Nov 25 13:57:56 2016
Host           : Linux vocms0302.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/scratch/tt8888tt/tmva
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
recoMuon_isGlobalMuon         recoMuon_isGlobalMuon         recoMuon_isGlobalMuon         recoMuon_isGlobalMuon                                           'I'    [0,1]
recoMuon_isPFMuon             recoMuon_isPFMuon             recoMuon_isPFMuon             recoMuon_isPFMuon                                               'I'    [0,1]
recoMuon_normalizedChi2       recoMuon_normalizedChi2       recoMuon_normalizedChi2       recoMuon_normalizedChi2                                         'F'    [-9,4288.34912109]
recoMuon_chi2LocalPosition    recoMuon_chi2LocalPosition    recoMuon_chi2LocalPosition    recoMuon_chi2LocalPosition                                      'F'    [0,75.5944137573]
recoMuon_trkKink              recoMuon_trkKink              recoMuon_trkKink              recoMuon_trkKink                                                'F'    [0,999]
recoMuon_segmentCompatibility recoMuon_segmentCompatibility recoMuon_segmentCompatibility recoMuon_segmentCompatibility                                   'F'    [0,1]
recoMuon_numberOfMatchedStations recoMuon_numberOfMatchedStations recoMuon_numberOfMatchedStations recoMuon_numberOfMatchedStations                                      'I'    [0,5]
recoMuon_numberOfValidMuonHits recoMuon_numberOfValidMuonHits recoMuon_numberOfValidMuonHits recoMuon_numberOfValidMuonHits                                    'I'    [-9,50]
recoMuon_pv0pos_dxy           recoMuon_pv0pos_dxy           recoMuon_pv0pos_dxy           recoMuon_pv0pos_dxy                                             'F'    [1.59960211477e-06,0.715790331364]
recoMuon_pv0pos_dz            recoMuon_pv0pos_dz            recoMuon_pv0pos_dz            recoMuon_pv0pos_dz                                              'F'    [6.67703204726e-07,226.065490723]
recoMuon_numberOfValidPixelHits recoMuon_numberOfValidPixelHits recoMuon_numberOfValidPixelHits recoMuon_numberOfValidPixelHits                                     'I'    [-9,11]
recoMuon_trackerLayersWithMeasurement recoMuon_trackerLayersWithMeasurement recoMuon_trackerLayersWithMeasurement recoMuon_trackerLayersWithMeasurement                                           'F'    [-9,12]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "recoMuon_isGlobalMuon", "recoMuon_isPFMuon", "recoMuon_normalizedChi2", "recoMuon_chi2LocalPosition", "recoMuon_trkKink", "recoMuon_segmentCompatibility", "recoMuon_numberOfMatchedStations", "recoMuon_numberOfValidMuonHits", "recoMuon_pv0pos_dxy", "recoMuon_pv0pos_dz", "recoMuon_numberOfValidPixelHits", "recoMuon_trackerLayersWithMeasurement" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'I';
      fType[7] = 'I';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'I';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[18][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][18];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 18; fWeights[1] = new double[18]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.21283924965412;
   fWeightMatrix0to1[1][0] = 1.80161241605278;
   fWeightMatrix0to1[2][0] = 1.36995354240133;
   fWeightMatrix0to1[3][0] = 2.10778652433544;
   fWeightMatrix0to1[4][0] = -2.09352364841765;
   fWeightMatrix0to1[5][0] = -1.45250805549833;
   fWeightMatrix0to1[6][0] = -0.755981107065645;
   fWeightMatrix0to1[7][0] = 1.85647819029442;
   fWeightMatrix0to1[8][0] = -1.03884215772444;
   fWeightMatrix0to1[9][0] = -0.980930456673607;
   fWeightMatrix0to1[10][0] = -2.16371018855622;
   fWeightMatrix0to1[11][0] = -1.12529687039982;
   fWeightMatrix0to1[12][0] = -0.377040757261744;
   fWeightMatrix0to1[13][0] = -0.380083535144973;
   fWeightMatrix0to1[14][0] = -0.652808508629187;
   fWeightMatrix0to1[15][0] = 0.809897115836897;
   fWeightMatrix0to1[16][0] = -0.458034364019753;
   fWeightMatrix0to1[0][1] = 1.00177037679991;
   fWeightMatrix0to1[1][1] = -0.0163847355434151;
   fWeightMatrix0to1[2][1] = 1.72864908357415;
   fWeightMatrix0to1[3][1] = 0.521765456797898;
   fWeightMatrix0to1[4][1] = -0.565239670815634;
   fWeightMatrix0to1[5][1] = 1.29416954599451;
   fWeightMatrix0to1[6][1] = 0.131974420788733;
   fWeightMatrix0to1[7][1] = -1.3391628932146;
   fWeightMatrix0to1[8][1] = 0.184193701240832;
   fWeightMatrix0to1[9][1] = 1.42236681394537;
   fWeightMatrix0to1[10][1] = -1.16818511148455;
   fWeightMatrix0to1[11][1] = -2.26192183588216;
   fWeightMatrix0to1[12][1] = 0.254349105700803;
   fWeightMatrix0to1[13][1] = 0.43628694194177;
   fWeightMatrix0to1[14][1] = 1.28636889467385;
   fWeightMatrix0to1[15][1] = -0.364348504927831;
   fWeightMatrix0to1[16][1] = -0.208990117053467;
   fWeightMatrix0to1[0][2] = 0.879333424802553;
   fWeightMatrix0to1[1][2] = -0.423950585741347;
   fWeightMatrix0to1[2][2] = -1.55522975432329;
   fWeightMatrix0to1[3][2] = 1.66028211055587;
   fWeightMatrix0to1[4][2] = -1.45563872616165;
   fWeightMatrix0to1[5][2] = 1.41159444794351;
   fWeightMatrix0to1[6][2] = 1.19899764330876;
   fWeightMatrix0to1[7][2] = 0.798683796631986;
   fWeightMatrix0to1[8][2] = 1.82577303665949;
   fWeightMatrix0to1[9][2] = 1.42222804886103;
   fWeightMatrix0to1[10][2] = -1.0037688738965;
   fWeightMatrix0to1[11][2] = -1.28757205950233;
   fWeightMatrix0to1[12][2] = 0.630621271671823;
   fWeightMatrix0to1[13][2] = 0.0706715513698973;
   fWeightMatrix0to1[14][2] = 1.54393777957797;
   fWeightMatrix0to1[15][2] = 1.49537419591772;
   fWeightMatrix0to1[16][2] = 1.5300951082167;
   fWeightMatrix0to1[0][3] = 1.75408429419175;
   fWeightMatrix0to1[1][3] = -1.83794327917382;
   fWeightMatrix0to1[2][3] = 1.20525201267684;
   fWeightMatrix0to1[3][3] = -2.0832682938767;
   fWeightMatrix0to1[4][3] = -0.92171899111937;
   fWeightMatrix0to1[5][3] = -1.46245507393258;
   fWeightMatrix0to1[6][3] = -1.76000488134797;
   fWeightMatrix0to1[7][3] = 1.63555981399953;
   fWeightMatrix0to1[8][3] = 0.35479171262658;
   fWeightMatrix0to1[9][3] = -1.48411098331881;
   fWeightMatrix0to1[10][3] = 0.052455962105413;
   fWeightMatrix0to1[11][3] = -0.163556854691663;
   fWeightMatrix0to1[12][3] = 0.752578107358768;
   fWeightMatrix0to1[13][3] = 1.98399158705397;
   fWeightMatrix0to1[14][3] = 0.128241909490903;
   fWeightMatrix0to1[15][3] = 0.125093275612641;
   fWeightMatrix0to1[16][3] = -1.25209577914132;
   fWeightMatrix0to1[0][4] = 0.65375998402194;
   fWeightMatrix0to1[1][4] = -0.999319711020069;
   fWeightMatrix0to1[2][4] = -0.893350088937683;
   fWeightMatrix0to1[3][4] = -1.65977292980894;
   fWeightMatrix0to1[4][4] = 0.640096856294813;
   fWeightMatrix0to1[5][4] = 1.46143975352147;
   fWeightMatrix0to1[6][4] = 1.33448958453044;
   fWeightMatrix0to1[7][4] = -0.316074852761053;
   fWeightMatrix0to1[8][4] = -1.2996159783029;
   fWeightMatrix0to1[9][4] = -2.07928763229936;
   fWeightMatrix0to1[10][4] = 1.54827717195465;
   fWeightMatrix0to1[11][4] = -0.112641042799985;
   fWeightMatrix0to1[12][4] = 2.47739171928691;
   fWeightMatrix0to1[13][4] = 0.539875167660451;
   fWeightMatrix0to1[14][4] = 1.66557963201844;
   fWeightMatrix0to1[15][4] = -0.710394302761383;
   fWeightMatrix0to1[16][4] = -0.918230961735733;
   fWeightMatrix0to1[0][5] = 0.665761454501072;
   fWeightMatrix0to1[1][5] = 1.04405877320039;
   fWeightMatrix0to1[2][5] = -0.903965994821468;
   fWeightMatrix0to1[3][5] = -0.647731541065319;
   fWeightMatrix0to1[4][5] = -1.73920264852089;
   fWeightMatrix0to1[5][5] = -1.58415016035474;
   fWeightMatrix0to1[6][5] = -0.101373243316231;
   fWeightMatrix0to1[7][5] = 1.50759296324282;
   fWeightMatrix0to1[8][5] = -3.46769270005256;
   fWeightMatrix0to1[9][5] = -0.737261485934242;
   fWeightMatrix0to1[10][5] = 1.7773050465382;
   fWeightMatrix0to1[11][5] = -1.73903464098507;
   fWeightMatrix0to1[12][5] = -2.21977372502206;
   fWeightMatrix0to1[13][5] = -1.5368443831953;
   fWeightMatrix0to1[14][5] = -0.87100541946131;
   fWeightMatrix0to1[15][5] = -1.89515468848234;
   fWeightMatrix0to1[16][5] = -1.66904454966877;
   fWeightMatrix0to1[0][6] = 0.792521054620847;
   fWeightMatrix0to1[1][6] = 1.52080526338938;
   fWeightMatrix0to1[2][6] = -0.973821218100281;
   fWeightMatrix0to1[3][6] = 2.12939171695914;
   fWeightMatrix0to1[4][6] = -1.45967936619274;
   fWeightMatrix0to1[5][6] = -0.436692952692832;
   fWeightMatrix0to1[6][6] = -0.0189875605583205;
   fWeightMatrix0to1[7][6] = 0.272462101733253;
   fWeightMatrix0to1[8][6] = -2.98938832382486;
   fWeightMatrix0to1[9][6] = -0.147078870935094;
   fWeightMatrix0to1[10][6] = 0.564712819652263;
   fWeightMatrix0to1[11][6] = 2.07124470129781;
   fWeightMatrix0to1[12][6] = -1.63041949678904;
   fWeightMatrix0to1[13][6] = 1.76685442110225;
   fWeightMatrix0to1[14][6] = -0.554024386004898;
   fWeightMatrix0to1[15][6] = -0.909922726272146;
   fWeightMatrix0to1[16][6] = 0.75831921381499;
   fWeightMatrix0to1[0][7] = -0.831799874768047;
   fWeightMatrix0to1[1][7] = -1.76461615845016;
   fWeightMatrix0to1[2][7] = 0.343335225018667;
   fWeightMatrix0to1[3][7] = 0.100957487493312;
   fWeightMatrix0to1[4][7] = 1.28240781129611;
   fWeightMatrix0to1[5][7] = 1.28366483551661;
   fWeightMatrix0to1[6][7] = -0.0108651278706826;
   fWeightMatrix0to1[7][7] = -0.41916992926276;
   fWeightMatrix0to1[8][7] = -0.0951819663682065;
   fWeightMatrix0to1[9][7] = -1.66564417280479;
   fWeightMatrix0to1[10][7] = 0.645126982809005;
   fWeightMatrix0to1[11][7] = 0.311307000629526;
   fWeightMatrix0to1[12][7] = -1.9179837228226;
   fWeightMatrix0to1[13][7] = 0.837869939597008;
   fWeightMatrix0to1[14][7] = -2.06295937641236;
   fWeightMatrix0to1[15][7] = 0.155541630332393;
   fWeightMatrix0to1[16][7] = 1.12461214846294;
   fWeightMatrix0to1[0][8] = 1.75524675096173;
   fWeightMatrix0to1[1][8] = -1.73995839767662;
   fWeightMatrix0to1[2][8] = -0.174224684810254;
   fWeightMatrix0to1[3][8] = 1.13805758321925;
   fWeightMatrix0to1[4][8] = 1.39340063072746;
   fWeightMatrix0to1[5][8] = -0.852740208429695;
   fWeightMatrix0to1[6][8] = -1.48044461945041;
   fWeightMatrix0to1[7][8] = -0.0856452660661965;
   fWeightMatrix0to1[8][8] = -0.204903989001732;
   fWeightMatrix0to1[9][8] = 1.52233137147167;
   fWeightMatrix0to1[10][8] = 1.58695526117366;
   fWeightMatrix0to1[11][8] = -0.421489146084179;
   fWeightMatrix0to1[12][8] = -0.312307645498181;
   fWeightMatrix0to1[13][8] = 0.100875887489793;
   fWeightMatrix0to1[14][8] = -0.301484466809484;
   fWeightMatrix0to1[15][8] = 0.471472381357225;
   fWeightMatrix0to1[16][8] = 1.79870586771127;
   fWeightMatrix0to1[0][9] = -0.433348133261431;
   fWeightMatrix0to1[1][9] = -0.740772404129305;
   fWeightMatrix0to1[2][9] = -0.0794432389669358;
   fWeightMatrix0to1[3][9] = 0.869134515679258;
   fWeightMatrix0to1[4][9] = 0.368145191413386;
   fWeightMatrix0to1[5][9] = 0.420901736116724;
   fWeightMatrix0to1[6][9] = -1.49881736919873;
   fWeightMatrix0to1[7][9] = 1.668523646394;
   fWeightMatrix0to1[8][9] = 1.15149021949595;
   fWeightMatrix0to1[9][9] = 0.454957927794242;
   fWeightMatrix0to1[10][9] = 0.844986163563603;
   fWeightMatrix0to1[11][9] = 0.847898100960563;
   fWeightMatrix0to1[12][9] = -0.309957599189619;
   fWeightMatrix0to1[13][9] = -0.619941156407672;
   fWeightMatrix0to1[14][9] = 2.10254663074751;
   fWeightMatrix0to1[15][9] = -1.01363365348731;
   fWeightMatrix0to1[16][9] = -0.599137113112031;
   fWeightMatrix0to1[0][10] = 2.33902788731905;
   fWeightMatrix0to1[1][10] = 1.04199827443725;
   fWeightMatrix0to1[2][10] = -0.104489430604648;
   fWeightMatrix0to1[3][10] = 1.67739320724793;
   fWeightMatrix0to1[4][10] = 1.90226979124076;
   fWeightMatrix0to1[5][10] = -1.68964281071586;
   fWeightMatrix0to1[6][10] = 0.654877827910744;
   fWeightMatrix0to1[7][10] = -0.0693850103615225;
   fWeightMatrix0to1[8][10] = -0.705660121854742;
   fWeightMatrix0to1[9][10] = -1.73791146685882;
   fWeightMatrix0to1[10][10] = -2.10856199076364;
   fWeightMatrix0to1[11][10] = 1.28149801497787;
   fWeightMatrix0to1[12][10] = 1.78642528767075;
   fWeightMatrix0to1[13][10] = -1.74445347367967;
   fWeightMatrix0to1[14][10] = -1.04252739491826;
   fWeightMatrix0to1[15][10] = -0.602474454966615;
   fWeightMatrix0to1[16][10] = 0.325855158968261;
   fWeightMatrix0to1[0][11] = 3.02267439764679;
   fWeightMatrix0to1[1][11] = -0.351457441976779;
   fWeightMatrix0to1[2][11] = -0.316334534199347;
   fWeightMatrix0to1[3][11] = -0.72655205937288;
   fWeightMatrix0to1[4][11] = 1.0108692434301;
   fWeightMatrix0to1[5][11] = 3.58329528268487;
   fWeightMatrix0to1[6][11] = 1.09181555067046;
   fWeightMatrix0to1[7][11] = 0.0858359226615225;
   fWeightMatrix0to1[8][11] = -3.01825564661885;
   fWeightMatrix0to1[9][11] = -2.23837837917682;
   fWeightMatrix0to1[10][11] = 0.336510246222073;
   fWeightMatrix0to1[11][11] = 2.23984302752769;
   fWeightMatrix0to1[12][11] = -1.17434152551973;
   fWeightMatrix0to1[13][11] = -0.648326363340651;
   fWeightMatrix0to1[14][11] = 1.0487917350045;
   fWeightMatrix0to1[15][11] = 9.33917216945504e-05;
   fWeightMatrix0to1[16][11] = -1.94772424834653;
   fWeightMatrix0to1[0][12] = 0.902453956879094;
   fWeightMatrix0to1[1][12] = 0.982828402111013;
   fWeightMatrix0to1[2][12] = -0.370413892808007;
   fWeightMatrix0to1[3][12] = -0.0548222661172764;
   fWeightMatrix0to1[4][12] = 1.88778595096862;
   fWeightMatrix0to1[5][12] = 0.737535542513974;
   fWeightMatrix0to1[6][12] = 0.497570177522299;
   fWeightMatrix0to1[7][12] = -0.238489673928956;
   fWeightMatrix0to1[8][12] = -1.8623512258294;
   fWeightMatrix0to1[9][12] = -1.06383097800163;
   fWeightMatrix0to1[10][12] = 1.97452281328186;
   fWeightMatrix0to1[11][12] = 0.990523815964397;
   fWeightMatrix0to1[12][12] = 0.888942814461693;
   fWeightMatrix0to1[13][12] = 0.204854031364967;
   fWeightMatrix0to1[14][12] = 1.86652618075548;
   fWeightMatrix0to1[15][12] = -1.69151787534684;
   fWeightMatrix0to1[16][12] = -1.26783325054213;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.54201482845538;
   fWeightMatrix1to2[0][1] = -1.63138094344902;
   fWeightMatrix1to2[0][2] = 0.258703193186276;
   fWeightMatrix1to2[0][3] = 1.49128399658014;
   fWeightMatrix1to2[0][4] = -0.831069010053289;
   fWeightMatrix1to2[0][5] = 2.85259202132442;
   fWeightMatrix1to2[0][6] = -0.435570736239512;
   fWeightMatrix1to2[0][7] = -1.40691720977953;
   fWeightMatrix1to2[0][8] = -3.0169979808074;
   fWeightMatrix1to2[0][9] = 0.92296833483129;
   fWeightMatrix1to2[0][10] = -2.00897780984107;
   fWeightMatrix1to2[0][11] = 3.141117372414;
   fWeightMatrix1to2[0][12] = -1.84026317854577;
   fWeightMatrix1to2[0][13] = 2.1198050380495;
   fWeightMatrix1to2[0][14] = -3.56356615456614;
   fWeightMatrix1to2[0][15] = 0.662187791424914;
   fWeightMatrix1to2[0][16] = -0.0829142087348052;
   fWeightMatrix1to2[0][17] = -1.79719163794962;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 1;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 1;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 1;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 1;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 1;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 1;
   fMin_1[0][2] = -9;
   fMax_1[0][2] = 4288.34912109;
   fMin_1[1][2] = -9;
   fMax_1[1][2] = 2930.43310547;
   fMin_1[2][2] = -9;
   fMax_1[2][2] = 4288.34912109;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 75.5944137573;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 52.0592079163;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 75.5944137573;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 999;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 999;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 999;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 5;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 4;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 5;
   fMin_1[0][7] = -9;
   fMax_1[0][7] = 50;
   fMin_1[1][7] = -9;
   fMax_1[1][7] = 25;
   fMin_1[2][7] = -9;
   fMax_1[2][7] = 50;
   fMin_1[0][8] = 1.59960211477e-06;
   fMax_1[0][8] = 0.0372492112219;
   fMin_1[1][8] = 5.41541703569e-06;
   fMax_1[1][8] = 0.715790331364;
   fMin_1[2][8] = 1.59960211477e-06;
   fMax_1[2][8] = 0.715790331364;
   fMin_1[0][9] = 6.67703204726e-07;
   fMax_1[0][9] = 20.2488441467;
   fMin_1[1][9] = 0.00580261694267;
   fMax_1[1][9] = 226.065490723;
   fMin_1[2][9] = 6.67703204726e-07;
   fMax_1[2][9] = 226.065490723;
   fMin_1[0][10] = 2;
   fMax_1[0][10] = 11;
   fMin_1[1][10] = -9;
   fMax_1[1][10] = 11;
   fMin_1[2][10] = -9;
   fMax_1[2][10] = 11;
   fMin_1[0][11] = 3;
   fMax_1[0][11] = 12;
   fMin_1[1][11] = -9;
   fMax_1[1][11] = 12;
   fMin_1[2][11] = -9;
   fMax_1[2][11] = 12;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
