// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/07       [395271]
Creator        : tt8888tt
Date           : Thu Jun  1 15:07:33 2017
Host           : Linux vocms029.cern.ch 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 16:56:37 CET 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/scratch/tt8888tt/isolation/src/MuonPerformance/MuonAnalyser/test/tmva
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
muon_isGlobalMuon             muon_isGlobalMuon             muon_isGlobalMuon             muon_isGlobalMuon                                               'I'    [0,1]
muon_isPFMuon                 muon_isPFMuon                 muon_isPFMuon                 muon_isPFMuon                                                   'I'    [0,1]
muon_normalizedChi2           muon_normalizedChi2           muon_normalizedChi2           muon_normalizedChi2                                             'F'    [-9,2555.92382812]
muon_chi2LocalPosition        muon_chi2LocalPosition        muon_chi2LocalPosition        muon_chi2LocalPosition                                          'F'    [0,42.4905090332]
muon_trkKink                  muon_trkKink                  muon_trkKink                  muon_trkKink                                                    'F'    [0,999]
muon_segmentCompatibility     muon_segmentCompatibility     muon_segmentCompatibility     muon_segmentCompatibility                                       'F'    [0,1]
muon_numberOfValidMuonHits    muon_numberOfValidMuonHits    muon_numberOfValidMuonHits    muon_numberOfValidMuonHits                                      'I'    [-9,52]
muon_numberOfMatchedStations  muon_numberOfMatchedStations  muon_numberOfMatchedStations  muon_numberOfMatchedStations                                    'I'    [0,5]
muon_pv0pos_dxy               muon_pv0pos_dxy               muon_pv0pos_dxy               muon_pv0pos_dxy                                                 'F'    [3.12640544564e-08,1.23298633099]
muon_pv0pos_dz                muon_pv0pos_dz                muon_pv0pos_dz                muon_pv0pos_dz                                                  'F'    [1.85389424701e-07,55.1179275513]
muon_numberOfValidPixelHits   muon_numberOfValidPixelHits   muon_numberOfValidPixelHits   muon_numberOfValidPixelHits                                     'I'    [-9,18]
muon_trackerLayersWithMeasurement muon_trackerLayersWithMeasurement muon_trackerLayersWithMeasurement muon_trackerLayersWithMeasurement                                       'F'    [-9,12]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "muon_isGlobalMuon", "muon_isPFMuon", "muon_normalizedChi2", "muon_chi2LocalPosition", "muon_trkKink", "muon_segmentCompatibility", "muon_numberOfValidMuonHits", "muon_numberOfMatchedStations", "muon_pv0pos_dxy", "muon_pv0pos_dz", "muon_numberOfValidPixelHits", "muon_trackerLayersWithMeasurement" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'I';
      fType[7] = 'I';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'I';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[18][13];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][18];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 13; fWeights[0] = new double[13]; 
   fLayerSize[1] = 18; fWeights[1] = new double[18]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0226992171790479;
   fWeightMatrix0to1[1][0] = 2.31912884865005;
   fWeightMatrix0to1[2][0] = 0.443916689709831;
   fWeightMatrix0to1[3][0] = 2.15384604901384;
   fWeightMatrix0to1[4][0] = -2.18989332852079;
   fWeightMatrix0to1[5][0] = -1.82749759373162;
   fWeightMatrix0to1[6][0] = -0.725255970887244;
   fWeightMatrix0to1[7][0] = 1.40065993990249;
   fWeightMatrix0to1[8][0] = -1.15267629609291;
   fWeightMatrix0to1[9][0] = -1.16327668852387;
   fWeightMatrix0to1[10][0] = -2.69269707712176;
   fWeightMatrix0to1[11][0] = -0.510038169878202;
   fWeightMatrix0to1[12][0] = -0.90183822130194;
   fWeightMatrix0to1[13][0] = 0.16717742577612;
   fWeightMatrix0to1[14][0] = 0.263877045860136;
   fWeightMatrix0to1[15][0] = 0.793919027744558;
   fWeightMatrix0to1[16][0] = -0.28609773548977;
   fWeightMatrix0to1[0][1] = 1.4957340350165;
   fWeightMatrix0to1[1][1] = 0.181389648484165;
   fWeightMatrix0to1[2][1] = 1.79593497644183;
   fWeightMatrix0to1[3][1] = -0.449443517288716;
   fWeightMatrix0to1[4][1] = -0.830412478508067;
   fWeightMatrix0to1[5][1] = -0.225245920573478;
   fWeightMatrix0to1[6][1] = 0.19790594900795;
   fWeightMatrix0to1[7][1] = -1.51528166873917;
   fWeightMatrix0to1[8][1] = -0.0168948552609615;
   fWeightMatrix0to1[9][1] = 2.93276335484252;
   fWeightMatrix0to1[10][1] = -0.587804983847466;
   fWeightMatrix0to1[11][1] = -1.85383131873122;
   fWeightMatrix0to1[12][1] = -0.551999343364422;
   fWeightMatrix0to1[13][1] = 0.874918295230265;
   fWeightMatrix0to1[14][1] = -0.00552659119398647;
   fWeightMatrix0to1[15][1] = 0.117424638458288;
   fWeightMatrix0to1[16][1] = -0.0450892289358209;
   fWeightMatrix0to1[0][2] = 0.180546254147671;
   fWeightMatrix0to1[1][2] = 0.29327403592517;
   fWeightMatrix0to1[2][2] = -1.57511477871797;
   fWeightMatrix0to1[3][2] = 1.40068898162394;
   fWeightMatrix0to1[4][2] = -1.2435925301343;
   fWeightMatrix0to1[5][2] = 1.94286250504634;
   fWeightMatrix0to1[6][2] = 1.28277873934632;
   fWeightMatrix0to1[7][2] = 1.22295765337314;
   fWeightMatrix0to1[8][2] = 1.95313822797433;
   fWeightMatrix0to1[9][2] = 0.592577841103877;
   fWeightMatrix0to1[10][2] = -1.67246913443634;
   fWeightMatrix0to1[11][2] = -1.58162082553446;
   fWeightMatrix0to1[12][2] = 0.363016024922118;
   fWeightMatrix0to1[13][2] = -0.444876733433892;
   fWeightMatrix0to1[14][2] = -1.04627625532699;
   fWeightMatrix0to1[15][2] = 1.46309781367314;
   fWeightMatrix0to1[16][2] = 1.706199715878;
   fWeightMatrix0to1[0][3] = 1.11251996984436;
   fWeightMatrix0to1[1][3] = -1.10661854487609;
   fWeightMatrix0to1[2][3] = 1.13529032882082;
   fWeightMatrix0to1[3][3] = -2.58116153699739;
   fWeightMatrix0to1[4][3] = -0.742705811006946;
   fWeightMatrix0to1[5][3] = -0.919490230348312;
   fWeightMatrix0to1[6][3] = -1.67246768247301;
   fWeightMatrix0to1[7][3] = 1.82301385243957;
   fWeightMatrix0to1[8][3] = 0.788213270683471;
   fWeightMatrix0to1[9][3] = -2.43907383288539;
   fWeightMatrix0to1[10][3] = -0.602509721449996;
   fWeightMatrix0to1[11][3] = -0.143870917114185;
   fWeightMatrix0to1[12][3] = 0.703993646344696;
   fWeightMatrix0to1[13][3] = 1.29074433986981;
   fWeightMatrix0to1[14][3] = -1.90925908049958;
   fWeightMatrix0to1[15][3] = 0.38956839047654;
   fWeightMatrix0to1[16][3] = -1.0800968014126;
   fWeightMatrix0to1[0][4] = 1.2682151944957;
   fWeightMatrix0to1[1][4] = -0.339764100008686;
   fWeightMatrix0to1[2][4] = -0.758401783528747;
   fWeightMatrix0to1[3][4] = -0.513062919954765;
   fWeightMatrix0to1[4][4] = -0.138477603079486;
   fWeightMatrix0to1[5][4] = 2.10394408059538;
   fWeightMatrix0to1[6][4] = 1.48166758957712;
   fWeightMatrix0to1[7][4] = -0.235223428890143;
   fWeightMatrix0to1[8][4] = -1.30131069285791;
   fWeightMatrix0to1[9][4] = -2.08682153922553;
   fWeightMatrix0to1[10][4] = 1.12566631225893;
   fWeightMatrix0to1[11][4] = 0.702149342952916;
   fWeightMatrix0to1[12][4] = 0.845975011439347;
   fWeightMatrix0to1[13][4] = 1.30025241863822;
   fWeightMatrix0to1[14][4] = 0.0916951247838349;
   fWeightMatrix0to1[15][4] = -0.859127672539215;
   fWeightMatrix0to1[16][4] = -0.748817948225969;
   fWeightMatrix0to1[0][5] = -0.864799292528987;
   fWeightMatrix0to1[1][5] = 1.274438673595;
   fWeightMatrix0to1[2][5] = -1.77116968357861;
   fWeightMatrix0to1[3][5] = -0.68248510359841;
   fWeightMatrix0to1[4][5] = -2.01024750355336;
   fWeightMatrix0to1[5][5] = -1.32524039102405;
   fWeightMatrix0to1[6][5] = -0.464416881224264;
   fWeightMatrix0to1[7][5] = 1.29454077337544;
   fWeightMatrix0to1[8][5] = -3.13739772903802;
   fWeightMatrix0to1[9][5] = -0.474442793099972;
   fWeightMatrix0to1[10][5] = 2.62016237083344;
   fWeightMatrix0to1[11][5] = -1.03707548372267;
   fWeightMatrix0to1[12][5] = -1.81588099877388;
   fWeightMatrix0to1[13][5] = -0.890282989741926;
   fWeightMatrix0to1[14][5] = -0.0291702637460589;
   fWeightMatrix0to1[15][5] = -3.2885125505055;
   fWeightMatrix0to1[16][5] = -1.40693513604762;
   fWeightMatrix0to1[0][6] = -0.163454060269188;
   fWeightMatrix0to1[1][6] = 2.15328432983978;
   fWeightMatrix0to1[2][6] = -0.713410196470779;
   fWeightMatrix0to1[3][6] = 2.33030828895635;
   fWeightMatrix0to1[4][6] = -1.6554646750334;
   fWeightMatrix0to1[5][6] = 0.369676498047458;
   fWeightMatrix0to1[6][6] = 0.0693891240498538;
   fWeightMatrix0to1[7][6] = 0.290190388902787;
   fWeightMatrix0to1[8][6] = -1.67040445107484;
   fWeightMatrix0to1[9][6] = -0.0516793944779584;
   fWeightMatrix0to1[10][6] = -0.779269932673582;
   fWeightMatrix0to1[11][6] = 1.07174796187425;
   fWeightMatrix0to1[12][6] = -1.4567825435842;
   fWeightMatrix0to1[13][6] = 1.91648803170508;
   fWeightMatrix0to1[14][6] = -1.4712692235762;
   fWeightMatrix0to1[15][6] = -0.867635671660693;
   fWeightMatrix0to1[16][6] = 0.927077525612466;
   fWeightMatrix0to1[0][7] = -1.2285027534777;
   fWeightMatrix0to1[1][7] = -0.935891187525899;
   fWeightMatrix0to1[2][7] = 0.824414173134823;
   fWeightMatrix0to1[3][7] = 0.0322249322278357;
   fWeightMatrix0to1[4][7] = 1.53557547731126;
   fWeightMatrix0to1[5][7] = 0.129433852698891;
   fWeightMatrix0to1[6][7] = -0.0743798693685246;
   fWeightMatrix0to1[7][7] = -0.441238502271231;
   fWeightMatrix0to1[8][7] = 1.40339550614462;
   fWeightMatrix0to1[9][7] = -0.671210015696549;
   fWeightMatrix0to1[10][7] = -0.2450080197824;
   fWeightMatrix0to1[11][7] = 0.725385142478274;
   fWeightMatrix0to1[12][7] = -2.64845557478018;
   fWeightMatrix0to1[13][7] = 0.966483384294932;
   fWeightMatrix0to1[14][7] = -0.670605168673633;
   fWeightMatrix0to1[15][7] = 0.319456969506272;
   fWeightMatrix0to1[16][7] = 1.38385329127818;
   fWeightMatrix0to1[0][8] = 2.87442244040998;
   fWeightMatrix0to1[1][8] = -2.92915822177333;
   fWeightMatrix0to1[2][8] = 1.15536195833741;
   fWeightMatrix0to1[3][8] = 1.42965478861745;
   fWeightMatrix0to1[4][8] = 1.4551092889258;
   fWeightMatrix0to1[5][8] = -0.790885221632777;
   fWeightMatrix0to1[6][8] = -1.31483927763244;
   fWeightMatrix0to1[7][8] = 0.115032079374208;
   fWeightMatrix0to1[8][8] = -2.75163233107973;
   fWeightMatrix0to1[9][8] = 1.69639406138832;
   fWeightMatrix0to1[10][8] = 2.86456015688297;
   fWeightMatrix0to1[11][8] = -0.340576352694028;
   fWeightMatrix0to1[12][8] = -0.946493621744395;
   fWeightMatrix0to1[13][8] = -0.077448654092051;
   fWeightMatrix0to1[14][8] = 0.788377317459028;
   fWeightMatrix0to1[15][8] = 0.200089161078723;
   fWeightMatrix0to1[16][8] = 1.50293640685128;
   fWeightMatrix0to1[0][9] = 0.723999961647424;
   fWeightMatrix0to1[1][9] = -2.01697783900981;
   fWeightMatrix0to1[2][9] = -0.408131590340997;
   fWeightMatrix0to1[3][9] = 0.800165237919344;
   fWeightMatrix0to1[4][9] = 0.316828160974897;
   fWeightMatrix0to1[5][9] = 0.577939638410727;
   fWeightMatrix0to1[6][9] = -1.36532464467671;
   fWeightMatrix0to1[7][9] = 1.77036060708633;
   fWeightMatrix0to1[8][9] = 1.16042185431455;
   fWeightMatrix0to1[9][9] = 2.33375511907051;
   fWeightMatrix0to1[10][9] = 5.27961232766629;
   fWeightMatrix0to1[11][9] = 0.67132840780412;
   fWeightMatrix0to1[12][9] = -0.747505869666751;
   fWeightMatrix0to1[13][9] = -0.618760283364528;
   fWeightMatrix0to1[14][9] = 7.937901161981;
   fWeightMatrix0to1[15][9] = -1.08154059871925;
   fWeightMatrix0to1[16][9] = -0.420494624606507;
   fWeightMatrix0to1[0][10] = 1.35066375642008;
   fWeightMatrix0to1[1][10] = 2.60372773773033;
   fWeightMatrix0to1[2][10] = -0.967009829471131;
   fWeightMatrix0to1[3][10] = 1.28352077035351;
   fWeightMatrix0to1[4][10] = 2.18477195702791;
   fWeightMatrix0to1[5][10] = -1.45382942564249;
   fWeightMatrix0to1[6][10] = 0.689925287102711;
   fWeightMatrix0to1[7][10] = -0.0965678123308735;
   fWeightMatrix0to1[8][10] = -0.624368204257545;
   fWeightMatrix0to1[9][10] = -3.45934097549876;
   fWeightMatrix0to1[10][10] = -0.836029298940517;
   fWeightMatrix0to1[11][10] = 0.872443388214337;
   fWeightMatrix0to1[12][10] = 2.05505472464619;
   fWeightMatrix0to1[13][10] = -1.84988890676805;
   fWeightMatrix0to1[14][10] = -1.09245702472738;
   fWeightMatrix0to1[15][10] = -1.05501979495099;
   fWeightMatrix0to1[16][10] = 0.313471254230494;
   fWeightMatrix0to1[0][11] = 4.3601644354966;
   fWeightMatrix0to1[1][11] = -0.298412532131457;
   fWeightMatrix0to1[2][11] = -0.419671674352825;
   fWeightMatrix0to1[3][11] = -1.20892392149112;
   fWeightMatrix0to1[4][11] = 1.22341363288809;
   fWeightMatrix0to1[5][11] = 3.8056842742476;
   fWeightMatrix0to1[6][11] = 1.30705870658485;
   fWeightMatrix0to1[7][11] = -0.0723642687940112;
   fWeightMatrix0to1[8][11] = -1.74281647733644;
   fWeightMatrix0to1[9][11] = -1.18134952598407;
   fWeightMatrix0to1[10][11] = 0.552132317560145;
   fWeightMatrix0to1[11][11] = 0.415713972844332;
   fWeightMatrix0to1[12][11] = -1.78824070903324;
   fWeightMatrix0to1[13][11] = -0.496134066855853;
   fWeightMatrix0to1[14][11] = 0.0263320133853929;
   fWeightMatrix0to1[15][11] = 0.539771876181349;
   fWeightMatrix0to1[16][11] = -2.12924183891453;
   fWeightMatrix0to1[0][12] = 1.5908706996176;
   fWeightMatrix0to1[1][12] = 0.264639215613112;
   fWeightMatrix0to1[2][12] = -0.419266787274332;
   fWeightMatrix0to1[3][12] = 0.248898794876834;
   fWeightMatrix0to1[4][12] = 1.66219332413931;
   fWeightMatrix0to1[5][12] = 0.235356385569275;
   fWeightMatrix0to1[6][12] = 0.413545704390931;
   fWeightMatrix0to1[7][12] = -0.651386565853834;
   fWeightMatrix0to1[8][12] = -2.01723171712654;
   fWeightMatrix0to1[9][12] = -0.300974741529947;
   fWeightMatrix0to1[10][12] = 2.63860897461918;
   fWeightMatrix0to1[11][12] = 1.28515793295528;
   fWeightMatrix0to1[12][12] = 1.17540340311482;
   fWeightMatrix0to1[13][12] = 0.731869901852125;
   fWeightMatrix0to1[14][12] = 4.50824835016252;
   fWeightMatrix0to1[15][12] = -1.71950276041008;
   fWeightMatrix0to1[16][12] = -1.44052444382629;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -3.22166743199848;
   fWeightMatrix1to2[0][1] = -3.43097726510814;
   fWeightMatrix1to2[0][2] = 1.3889578136154;
   fWeightMatrix1to2[0][3] = 1.46079757222392;
   fWeightMatrix1to2[0][4] = -1.72507975150798;
   fWeightMatrix1to2[0][5] = 3.71782930655481;
   fWeightMatrix1to2[0][6] = 1.05926831830289;
   fWeightMatrix1to2[0][7] = -2.75873353492603;
   fWeightMatrix1to2[0][8] = -3.45211506597131;
   fWeightMatrix1to2[0][9] = 4.03200067525295;
   fWeightMatrix1to2[0][10] = -3.24796572391927;
   fWeightMatrix1to2[0][11] = 2.25155786469625;
   fWeightMatrix1to2[0][12] = -2.15367191933895;
   fWeightMatrix1to2[0][13] = 1.33426940450181;
   fWeightMatrix1to2[0][14] = -4.4390219993525;
   fWeightMatrix1to2[0][15] = -2.23150729822871;
   fWeightMatrix1to2[0][16] = -0.783822845736928;
   fWeightMatrix1to2[0][17] = -0.314655144906213;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 1;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 1;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 1;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 1;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 1;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 1;
   fMin_1[0][2] = -9;
   fMax_1[0][2] = 2555.92382812;
   fMin_1[1][2] = -9;
   fMax_1[1][2] = 12.2035303116;
   fMin_1[2][2] = -9;
   fMax_1[2][2] = 2555.92382812;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 42.4905090332;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 26.0736675262;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 42.4905090332;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 999;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 278.454284668;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 999;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = -9;
   fMax_1[0][6] = 52;
   fMin_1[1][6] = -9;
   fMax_1[1][6] = 19;
   fMin_1[2][6] = -9;
   fMax_1[2][6] = 52;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 4;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 5;
   fMin_1[0][8] = 3.12640544564e-08;
   fMax_1[0][8] = 1.23298633099;
   fMin_1[1][8] = 1.74505912582e-05;
   fMax_1[1][8] = 1.0960559845;
   fMin_1[2][8] = 3.12640544564e-08;
   fMax_1[2][8] = 1.23298633099;
   fMin_1[0][9] = 1.85389424701e-07;
   fMax_1[0][9] = 55.1179275513;
   fMin_1[1][9] = 0.00552723556757;
   fMax_1[1][9] = 20.3067913055;
   fMin_1[2][9] = 1.85389424701e-07;
   fMax_1[2][9] = 55.1179275513;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 18;
   fMin_1[1][10] = -9;
   fMax_1[1][10] = 18;
   fMin_1[2][10] = -9;
   fMax_1[2][10] = 18;
   fMin_1[0][11] = 4;
   fMax_1[0][11] = 12;
   fMin_1[1][11] = -9;
   fMax_1[1][11] = 12;
   fMin_1[2][11] = -9;
   fMax_1[2][11] = 12;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
